export const ACTIONS_STATES = {
  START_GAME: "START GAME",
  WAITING_FOR_FIRST_USER: "WAITING_FOR_FIRST_USER",
  WAITING_FOR_CARD_SELECTION: "WAITING_FOR_CARD_SELECTION",
  WAITING_FOR_CAPTURE_QUESTION: "WAITING_FOR_CAPTURE_QUESTION",
  WAITING_FOR_USER_ANSWER: "WAITING_FOR_USER_ANSWER",
  FINISH_GAME: "FINISH GAME",
};
